### PR TITLE
adds support for Jekyll '{% highlight %}' codeblocks

### PR DESCRIPTION
**Pull request by gkemmey**
Jekyll has code blocks of the format:

```
{% highlight js %}
// cool javascript stuff
{% endhighlight %}
```

Jekyll uses [Pygments](http://pygments.org/) for syntax highlighting out-of-the-box, so I don't know if all the words would match as is (i.e `sql` is `mysql` in pygments). 

Anyway, I use `Markdown Extended`, but wanted it to also syntax highlight code when editing Jekyll blog files so this is what I've been using.

### CODE REVIEW

**Comment by jonschlinkert** [comment]
wow this is a great pr! nice work. Have you experienced any performance issue with the extra matching? it looks like there shouldn't be any problems.

**Comment by gkemmey** [comment]
I haven't, but I've just done some local testing on my various personal Markdown files. Any suggestions for trying something more exhaustive?

**Comment by jonschlinkert** [comment]
No, I wish I did lol. Would be nice if there was an easy way to run unit tests on packages. I'll pull this down asap and try to get it merged. Sorry for the delay but might be Mon. before I'll have a chance to review. thanks again!

**Comment by gkemmey** [comment]
No worries, my pleasure!

**Comment by jonschlinkert** [comment]
thanks again!

**Pull request merged**
