### PR TITLE
Adds support for `INI` and `Nginx` syntax

### PR DESCRIPTION
**Pull request by SuperPaintman**
examplemd

### CODE REVIEW

**Comment by SuperPaintman** [comment]
+ Erlang

**Comment by jonschlinkert** [comment]
I added you as a collab. Feel free to merge, and please add yourself to a collaborators section in the readme if you want!

**Comment by jonschlinkert** [comment]
same with sublime-monokai-extended

**Comment by SuperPaintman** [comment]
Oh, it's very kind of you

**Comment by jonschlinkert** [comment]
Thank you, but you are indeed a collaborator :) that distinction is all yours and I appreciate it. Besides changing colors or current behavior (I like my colors lol), feel free to make yourself at home!

**Comment by SuperPaintman** [comment]
Thanks!

**Pull request merged**
