### PR TITLE
Add syntax highlighting inside Jekyll's highlight tags, plus Kramdown support

### PR DESCRIPTION
**Pull request by aldanor**
Apparently, no ST packages currently provide proper syntax highlighting inside [Jekyll's code highlight blocks](http://jekyllrb.com/docs/templates/#code-snippet-highlighting) and inside Kramdown [block attributes](http://kramdown.gettalong.org/quickref.html#block-attributes) – this is what GitHub Pages [uses](https://pages.github.com/versions) so there's sure some demand for it :)

This PR adds some basic Kramdown highlighting plus source code highlighting inside `highlight` and `endhighlight` Liquid tags.

markdown-jekyll-kramdown

### CODE REVIEW

**Comment by aldanor** [comment]
Edit: I've just noticed Kramdown inline attributes were somewhat covered in #87 which hasn't been merged it, but I believe this version is a bit more granular.

**Comment by jonschlinkert** [comment]
This is great! thanks! I'll get this merged asap. I'll try tonight be it might be tomorrow.

**Comment by aldanor** [comment]
Changed liquid tags / kramdown block attributes highlighting to `comment.block.html` since `meta.block-level.markdown markup.raw.block.markdown` often overlaps with normal code highlighting in many themes (e.g. see the first image in this PR). This way it's more faded out and easier to tell where the code blocks start and end.

markdown-jekyll-kramdown-2

**Comment by aldanor** [comment]
@jonschlinkert :wave: what do you think?

Let me know if you have any concerns re: this PR, would love to see this get merged, been using it myself with great success :)

**Comment by jonschlinkert** [comment]
No concerns at all, looks great, I just need a little time to use it to weed out bugs if any exist. give me a day or two.

**Comment by aldanor** [comment]
No worries, thanks! Looking forward to the review then

**Comment by aldanor** [comment]
:octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: 

^ these octocats miss syntax highlighting!

**Comment by jonschlinkert** [comment]
sorry it has taken so long to get back to you on this. There are some issues that I was hoping to look into but haven't had time. Here is a screen of one issue I found:

**before**

This is what it should look like:

screen shot 2015-10-12 at 5 49 59 am

**after**

This is what it looked like after enabling your changes:

screen shot 2015-10-12 at 5 51 35 am

**Comment by jonschlinkert** [comment]
closing based on age and no response to my last comment. I'd be happy to revisit if we can smooth out the edge cases. thanks

**Pull request closed without merging**
